######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 1 12:57:44 2012
######################################################################

TEMPLATE = subdirs

# Directories
components.path = $$[QT_INSTALL_IMPORTS]/
components.files = Ubuntu
INSTALLS += components

