######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 1 12:59:31 2012
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += modules/qt-components-ubuntu.pro
