#!/usr/bin/python
#
# Copyright 2012 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import subprocess
import os
import os.path
import sys

global _BLACKLIST_DIR, _BLACKLIST_FILE
_BLACKLIST_DIR = ['.bzr','debian']
_BLACKLIST_FILE = ['Makefile','.bzrignore','COPYING','README','NEWS']
_BLACKLIST_FILETYPE = ["qml~","pyc","png"]

###############################################
def listFiles(targetpath):
  global _BLACKLIST_DIR, _BLACKLIST_FILE, _BLACKLIST_FILETYPE
  retval = []
  for root, dirs, files in os.walk(targetpath):

    # check blacklisted dirs
    for blackdir in _BLACKLIST_DIR:
      if blackdir in dirs:
        dirs.remove(blackdir)

    # check blacklisted files
    for blackfile in _BLACKLIST_FILE:
      if blackfile in files:
        files.remove(blackfile)
   
    for filename in files:
#      print "adding %s" % os.path.join(root,filename)
      match = 0
      for blacktype in _BLACKLIST_FILETYPE:
        if filename.endswith(blacktype):
           match += 1
        else:
          continue
      if match==0:
        retval.append(os.path.join(root,filename))

  return retval   
## eof listFiles

def license(fileName):
  p = subprocess.Popen(["licensecheck","--copyright","-m",fileName], stdout=subprocess.PIPE)
  return p.communicate()[0].strip().split("\t")

# lets list files in the project
projectFiles = listFiles("../../")

#print projectFiles
# lets get the license and copyright for every file
licenses = {}
copyrights = {}
for projectFile in projectFiles:
  try:  
    filename,file_license,file_copyright = license(projectFile)
  except ValueError:
    print projectFile
    sys.exit(1)
  if not licenses.has_key(file_license):
    licenses[file_license] = 1
  else:
    licenses[file_license] += 1

  if not copyrights.has_key(file_copyright):
    copyrights[file_copyright] = 1
  else:
    copyrights[file_copyright] += 1

print
print "Found %s files" % len(projectFiles)
print
print "Copyrights:" 
for key in copyrights.keys():
  print "%s = %s" % (key,copyrights[key])
print
print "Licenses:"
for key in licenses.keys():
  print "%s = %s" % (key,licenses[key])

print
